#!/bin/bash
kind=$1
song=$2
[ "$song" != "" ] || song=`mocp -i | grep SongTitle | awk {'gsub("SongTitle: ", ""); print $0'}`

file=$kind-favourites.txt
msg="added '$song' to $1"

cd ~/various
echo "$song" >> $file
git add $file          2>&1 >/dev/null
git ci -m "$msg"       2>&1 >/dev/null
git pull --rebase      2>&1 >/dev/null
git push origin master 2>&1 >/dev/null
echo $msg
